### ISSUE TITLE
 'NoneType' and 'str'

### ISSUE THREAD

**Issue by Daniel-DHu** [federicovergallo/SUMO-changing-lane-agent#12]
**I have this problem:**
**please help me, thank u!**

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    agent.train(env)
  File "D:\02Office_software\Sumo\Github\SUMO-changing-lane-agent-master\a2c.py", line 106, in train
    next_obs = env.reset(gui=True, numVehicles=25)
  File "D:\02Office_software\Sumo\Github\SUMO-changing-lane-agent-master\gym_sumo\envs\sumo_env.py", line 327, in reset
    self.start(gui, numVehicles, vType)
  File "D:\02Office_software\Sumo\Github\SUMO-changing-lane-agent-master\gym_sumo\envs\sumo_env.py", line 64, in start
    sumoBinary = home + "/gitprograms/sumo/bin/sumo-gui"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by federicovergallo** [comment]
Hi,

Beware that repo does not support Windows. In your case, the os library is failing to get the HOME macro (line 61 of the same file). Please set that macro and change the front slash with the back slash in other strings cause you'll have issues for file paths

**Comment by Daniel-DHu** [comment]
Thank u very much!




Dong&nbsp;Hu
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "federicovergallo/SUMO-changing-lane-agent"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 晚上9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [federicovergallo/SUMO-changing-lane-agent]  'NoneType' and 'str' (Issue #12)





 
Hi,
 
Beware that repo does not support Windows. In your case, the os library is failing to get the HOME macro (line 61 of the same file). Please set that macro and change the front slash with the back slash in other strings cause you'll have issues for file paths
