### ISSUE TITLE
 raise error.UnregisteredEnv('No registered env with id: {}'.format(id)) gym.error.UnregisteredEnv: No registered env with id: gym_sumo-v0

### ISSUE THREAD

**Issue by Yangli0505** [federicovergallo/SUMO-changing-lane-agent#2]
How to solve this error?

**Comment by federicovergallo** [comment]
I guess you didn't install the gym-sumo custom environment. You have to
locate yourself in gym_sumo/ folder (or gym_sumo/gym_sumo/) and then
install it via  pip install -e gym_sumo


Il giorno sab 20 mar 2021 alle ore 09:58 Yang0505 ***@***.***>
ha scritto:

**Comment by Yangli0505** [comment]
Thanks, solved it!

**Comment by risbansal** [comment]
Hello,

I am getting the following error when I run pip install -e gym_sumo

ERROR: gym_sumo/ is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

I am in the gym_sumo/gym_sumo folder in my terminal.

Can someone please help me solve this?

**Comment by Yangli0505** [comment]
i guess you can check the directory of the folder, 
and locate yourself in gym_sumo/ folder (or gym_sumo/gym_sumo/) and then install it via  pip install -e gym_sumo.

**Comment by risbansal** [comment]
Hello,

Thankyou for your reply. But as I mentioned in my question, I have already made sure that I am in the gym_sumo/gym_sumo folder. But I am still facing this issue. Can you please help me understand what the issue is about?

**Comment by Yangli0505** [comment]
maybe you could try in the gym_sumo/ folder instead of the "gym_sumo/gym_sumo"
folder
Best regards,

Yang Li
*Email: ***@***.***


Rishita Bansal ***@***.***> 于2024年5月9日周四 03:19写道：

**Comment by risbansal** [comment]
Yes I tried that too. I got the following error there:

ERROR: /change_lane_DQN-master/gym_sumo/gym_sumo does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

I also tried running another gym custom environment project and that worked well for me. I did not have to do pip -e  for that one. 

Basically when I run test.py.  I get teh error in this line:
env = gym.make('gym_sumo-v0')

**Comment by risbansal** [comment]
Hello,
I have tried that as well. But it did not work. I tried reinstalling all packaes again with proper version control in my virtual env. This time pip install -e sumo_gym worked. But I still get the following error when I run the code:
raise error.UnregisteredEnv('No registered env with id: {}'.format(id)) gym.error.UnregisteredEnv: No registered env with id: gym_sumo-v0
